---
title: "data_exploration"
author: "Abigail Beasley"
date: "2025-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Exploration

```{r}
library(tidyverse)
```

```{r load data}
data <- read.csv("data/healthcare_dataset.csv")
```

```{r}
is.numeric(data$Age)
is.numeric(data$Billing.Amount)
```

```{r}
# column names
names(data)
```

```{r}
# admission counts by gender
ggplot(data, aes(x=Admission.Type, fill=Gender)) +
  geom_bar(position='stack') +
  scale_fill_manual(values = c("Male" = "lightblue", "Female" = "orange")) +
  theme_minimal() +
  labs(title='Hospital Visits by Admission Type and Gender')
```

```{r}
# billing by type of admission
ggplot(data, aes(x=Admission.Type,y=Billing.Amount)) +
  stat_summary(fun.y=mean, geom='bar', fill='lightblue') +
  theme_minimal()+
  labs(title='Billing Amount By Admission Type')
  
```

```{r}
ggplot(data, aes(x=Gender,y=Billing.Amount)) +
  stat_summary(fun.y=mean, geom='bar', fill='lightblue') +
  labs(title='Average Billing Amount by Gender')
```

```{r}
# billing by type of admission
ggplot(data, aes(x=Age,y=Billing.Amount, fill=Gender)) +
  stat_summary(fun.y=mean, geom='bar', alpha=.7) +
  theme_minimal()+
  labs(title='Billing Amount By Age and Gender')

```

```{r}
# Condition by Gender
ggplot(data, aes(x=Medical.Condition, fill=Gender)) +
  geom_bar(position='stack') +
  scale_fill_manual(values = c("Male" = "lightblue", "Female" = "orange")) +
  theme_minimal() +
  labs(title='Hospital Visits by Condition and Gender')

```
```{r}
# billing by condition
ggplot(data, aes(x=Medical.Condition,y=Billing.Amount, fill=Gender)) +
  stat_summary(fun.y=mean, geom='bar', alpha=.7) +
  theme_minimal()+
  labs(title='Billing Amount By Condition Type and Gender')

```
```{r}
# type of condition by age
# billing by condition
ggplot(data, aes(x=Age,fill=Medical.Condition)) +
  stat_count() +
  labs(title='Medical Condition Counts By Age') +
  theme_minimal()

```
